# Generated by Django 4.0.3 on 2022-04-03 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=80, verbose_name='notification_description')),
                ('value_time', models.PositiveIntegerField(blank=True, null=True, verbose_name='notification_value_time')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='event_name')),
                ('start_datetime', models.DateTimeField(verbose_name='event_start_datetime')),
                ('end_datetime', models.DateTimeField(blank=True, verbose_name='event_end_datetime')),
                ('notification', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='events.notification', verbose_name='notification_event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
