# Generated by Django 3.2.12 on 2022-04-11 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_alter_customuser_country'),
        ('events', '0002_add_default_value_for_Notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country_holiday',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_event', to='accounts.country'),
        ),
        migrations.AddField(
            model_name='event',
            name='official_holiday',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=100, verbose_name='event_name'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='custom_user_event', to=settings.AUTH_USER_MODEL),
        ),
    ]
