# Generated by Django 3.2.12 on 2022-04-16 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20220411_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='official_holiday',
            field=models.BooleanField(choices=[(False, 'Show only custom events'), (True, 'Show only official holidays events')], db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='CustomUserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_status', models.BooleanField(db_index=True, default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_user_event', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_user_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='custom_user_event', through='events.CustomUserEvent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='customuserevent',
            constraint=models.UniqueConstraint(fields=('user', 'event'), name='user_event_unique'),
        ),
    ]
