version: '3.8'

services:
  db_postgres:
    image: postgres:13.0-alpine
    volumes:
      - static:/static
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  db_redis:
    image: redis:7.0.4-alpine
    volumes:
      - static:/static
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db_postgres
  nginx:
    build: ./nginx
    volumes:
      - .:/nginx
    ports:
      - 8084:80
    depends_on:
      - web

volumes:
  static: